### PR TITLE
add noetic base image

### PR DESCRIPTION
**Pull request by mhwasil**
Add noetic base image

### CODE REVIEW

**Comment by argenos** [comment]
Looks good to me. I don't think Travis can run your branch from a fork though; since you have write access can you push to a branch within the repo? Once the build passes I'd say you're good to merge

**Comment by mhwasil** [comment]
it was successful in `travis-build` branch
should I merge it from `travis-build` branch or from this pr? @argenos @sthoduka

**Comment by argenos** [comment]
I think it's still not passing: https://travis-ci.com/github/b-it-bots/docker/jobs/370672278

**Comment by mhwasil** [comment]
> I think it's still not passing: https://travis-ci.com/github/b-it-bots/docker/jobs/370672278

ah,, yeah. I did not update the `industrial` image yet

**Comment by mhwasil** [comment]
Some dependencies do not have noetic dist yet, and some of them are still in `dev`,
so I will keep this pr open until the dependencies with noetic distribution are available.

**Comment by argenos** [comment]
Sounds good, I'll mark it as a draft so I don't get reminders until it's ready to merge.

**Pull request merged**
